---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	requirements_analysis(requirements_analysis)
	architecture_design(architecture_design)
	database_design(database_design)
	api_design(api_design)
	backend_generation(backend_generation)
	frontend_generation(frontend_generation)
	code_review(code_review)
	code_refinement(code_refinement)
	test_generation(test_generation)
	documentation(documentation)
	__end__([<p>__end__</p>]):::last
	__start__ --> requirements_analysis;
	api_design --> backend_generation;
	api_design --> documentation;
	api_design --> frontend_generation;
	architecture_design --> api_design;
	architecture_design --> database_design;
	architecture_design --> documentation;
	architecture_design --> frontend_generation;
	backend_generation --> code_review;
	code_refinement --> test_generation;
	code_review --> code_refinement;
	database_design --> backend_generation;
	frontend_generation --> code_review;
	requirements_analysis --> api_design;
	requirements_analysis --> architecture_design;
	requirements_analysis --> database_design;
	documentation --> __end__;
	test_generation --> __end__;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
