import React from "react";
import { ChecklistLayout } from "../../layouts/onboarding/ChecklistLayout.tsx";

export default {
  title: "Layouts/Onboarding/ChecklistLayout",
  component: ChecklistLayout,
  parameters: {
    layout: "fullscreen",
  },
};

const mockTopic = {
  id: "ai-governance-checklist",
  title: "AI Governance Policy",
  subtitle: "What You Can — and Cannot — Do with GenAI Tools",
  color: "#0891B2",
  colorLight: "#22D3EE",
  colorGlow: "rgba(8,145,178,0.3)",
  icon: "🏛️",
  order: "02",
  approved: [
    {
      icon: "✅",
      title: "Code Completion & Suggestions",
      desc: "Use AI-assisted code completion (Copilot, Cursor) for boilerplate, repetitive logic, and known patterns. All output must be reviewed before commit.",
    },
    {
      icon: "✅",
      title: "Prompt-Assisted Drafting",
      desc: "Use Claude or GPT-4 to draft documentation, comments, test cases, and commit messages. Treat output as a first draft requiring human review.",
    },
    {
      icon: "✅",
      title: "Context-Enriched Code Review",
      desc: "Feed architecture docs and coding standards into prompts to produce higher-fidelity AI suggestions aligned with project conventions.",
    },
    {
      icon: "✅",
      title: "Test Scaffolding",
      desc: "Generate pytest fixtures, mock objects, and edge-case test stubs via AI. Validate logic independently before committing.",
    },
  ],
  awareness: [
    {
      icon: "⚠️",
      title: "AI-Summarized Meetings",
      desc: "Transcription and summary tools are permitted but must not capture classified or client-confidential discussions without prior approval.",
    },
  ],
  forbidden: [
    {
      icon: "🚫",
      title: "Submitting Unreviewed AI Output",
      desc: "Never commit, deploy, or deliver code or documents generated by AI without a human review step. All AI output is untrusted input by default.",
    },
    {
      icon: "🚫",
      title: "Entering CUI or PII into Public Models",
      desc: "Controlled Unclassified Information, PII, and client data must never be entered into consumer AI tools. Use approved enterprise endpoints only.",
    },
    {
      icon: "🚫",
      title: "Bypassing Security Review via AI",
      desc: "AI-generated authentication, authorization, or cryptographic code requires mandatory security reviewer sign-off regardless of apparent correctness.",
    },
    {
      icon: "🚫",
      title: "Using AI to Override ADR Decisions",
      desc: "Architectural decisions documented in ADRs cannot be reversed solely on the basis of an AI recommendation. Escalate to the architect.",
    },
  ],
  callout: "AI accelerates execution. Humans own every decision. That is not a constraint — it is the governance model.",
};

export const Default = {
  args: {
    topic: mockTopic,
    onBack: () => window.history.back(),
  },
};
