// ─── Onboarding Deck ───
// AI-Assisted Developer Workflow — 7 modular topics
// Gamma-inspired dark/black + orange/amber aesthetic.
export const themeId = "gamma-dark";

export const sprintNodes = [
  { abbr: "RQ", label: "Requirements", t: 0 },
  { abbr: "PL", label: "Planning", t: 0.17 },
  { abbr: "EX", label: "Execution", t: 0.33 },
  { abbr: "UT", label: "Unit Tests", t: 0.5 },
  { abbr: "E2E", label: "Integration", t: 0.67 },
  { abbr: "RV", label: "Review", t: 0.83 },
];

export const contentSlides = [
  {
    id: "expectations",
    order: 1,
    layout: "info-cards",
    title: "Expectations & Standards",
    subtitle: "What every team member must know on day one.",
    color: "#F97316",
    colorLight: "#FB923C",
    colorGlow: "rgba(249,115,22,0.3)",
    icon: "📋",
    headline: "Team Expectations",
    subheadline: "AI accelerates us — humans govern the outcome.",
    banner: "Every team member is responsible for the quality, security, and correctness of the work they produce — regardless of whether AI assisted in creating it. AI is a tool, not a teammate. You own the output.",
    cards: [
      { stat: "100%", statLabel: "Human Owned", title: "You Own Every Line", body: "AI-generated code ships under your name. You are accountable for understanding, reviewing, and validating every artifact before it leaves your workstation — no exceptions." },
      { stat: "Zero", statLabel: "Tolerance", title: "No Sensitive Data in AI", body: "Never paste CUI, PII, credentials, API keys, or any data classified above public into any AI tool. This is a hard stop. Violations are reportable incidents." },
      { stat: "1 wk", statLabel: "Sprint Cadence", title: "AI-Modified Sprints", body: "We run 1-week sprints with AI acceleration baked in. Higher velocity expectations but more frequent checkpoints. Every MR goes through human review." },
      { stat: "~95%", statLabel: "Predictability", title: "Complete Tickets Required", body: "AI tools produce better output from better input. Tickets must have fully fleshed out acceptance criteria, technical context, and data models before development begins." },
    ],
    callout: "Speed without governance is recklessness. Governance without speed is irrelevance. We do both.",
  },
  {
    id: "tools",
    order: 2,
    layout: "checklist",
    title: "Tools & Guardrails",
    subtitle: "What's approved, what's restricted, and where the lines are.",
    color: "#FBBF24",
    colorLight: "#FDE68A",
    colorGlow: "rgba(251,191,36,0.3)",
    icon: "🛡️",
    headline: "Approved Tools & Boundaries",
    approved: [
      { icon: "✅", title: "GitHub Copilot", desc: "Primary dev tool and general-use AI for experienced users. Autocomplete, inline chat, planning mode, agent mode, sub-agents — all in VS Code." },
      { icon: "✅", title: "Sidekick", desc: "General-purpose AI assistant across all roles. Custom Skills development and integrations for team-specific workflows." },
      { icon: "✅", title: "M365 Copilot", desc: "Full Office suite — Word (doc drafting), PowerPoint (decks), Excel (data analysis), Designer (visuals), Outlook, Teams." },
      { icon: "✅", title: "VS Code", desc: "Primary IDE for AI-assisted workflows. Planning mode, agent mode, sub-agent orchestration, MCP server integration." },
      { icon: "✅", title: "Visual Studio", desc: ".NET / Razor Pages development. Copilot available but agent/planning mode features differ from VS Code — know the differences." },
    ],
    forbidden: [
      { icon: "🚫", title: "Loading CUI/FOUO Data", desc: "Never input Controlled Unclassified Information into any AI tool — cloud-hosted or local. Full stop." },
      { icon: "🚫", title: "PII in Prompts", desc: "No real names, SSNs, case numbers, beneficiary data, or any personally identifiable information in any AI context." },
      { icon: "🚫", title: "Production Credentials", desc: "Never paste API keys, tokens, passwords, connection strings, or secrets into AI tools. Use placeholders." },
      { icon: "🚫", title: "Unapproved Tools", desc: "No personal free-tier AI tools for work tasks. No browser extensions that send code to unknown endpoints." },
      { icon: "🚫", title: "Blind Copy-Paste", desc: "Never paste AI output into production without reading, understanding, and testing it first. You own it." },
    ],
    callout: "The tools are powerful. The guardrails are non-negotiable. Internalize both.",
  },
  {
    id: "devworkflow",
    order: 3,
    layout: "workflow",
    title: "Developer Workflow",
    subtitle: "From ticket to merge request — the full AI-assisted loop.",
    color: "#A855F7",
    colorLight: "#C084FC",
    colorGlow: "rgba(168,85,247,0.3)",
    icon: "⚙️",
    headline: "The AI-Assisted Development Loop",
    subheadline: "Each step has a human checkpoint. AI accelerates — it never decides.",
    steps: [
      { num: "01", title: "Ticket Requirements", type: "human", body: "Start with a fully fleshed out ticket. Acceptance criteria must be specific, testable, and include edge cases. Include data models, API contracts, and UI mockups where applicable.", tip: "If the ticket isn't complete, push it back. Incomplete tickets produce incomplete AI output." },
      { num: "02", title: "Planning Mode", type: "ai", body: "Use VS Code Copilot planning mode to develop a detailed implementation plan. Feed it ticket requirements, architecture docs, coding standards, and relevant codebase context.", tip: "Have it probe for edge cases, integration risks, and missing requirements. The plan is the product — code gen is just execution." },
      { num: "03", title: "Sub-Agent Execution", type: "ai", body: "Break the plan into granular tasks. Use multiple models and specialized personas: a code generator, a test writer, a reviewer. Each sub-agent operates on a well-scoped piece of the plan.", tip: "Match model to task strength. Use Sidekick Skills and MCP servers to encode team conventions." },
      { num: "04", title: "Unit Test Generation", type: "ai", body: "Generate unit tests alongside implementation. Cover happy paths, edge cases, error handling, and boundary conditions.", tip: "Pattern: 'Write unit tests for [function]. Cover: happy path, null input, boundary values, error states. Use [framework]. Mock [dependencies].'" },
      { num: "05", title: "Integration & E2E Tests", type: "ai", body: "Generate Playwright tests for critical user flows on Razor Pages front-end. Validate selectors against actual UI. Include in GitLab CI/CD pipeline.", tip: "Have AI read the Razor Page code first. Devs can also use Playwright to investigate how defects present to end users." },
      { num: "06", title: "Multi-Angle Code Review", type: "human", body: "Run AI-assisted code reviews from multiple perspectives before the human MR review: correctness, security/vulnerability, performance, and adversarial/antagonistic review.", tip: "Adversarial prompt: 'You are a hostile code reviewer. Find every way this could fail, leak data, or be exploited. Be ruthless.'" },
      { num: "07", title: "MR Creation & Review", type: "human", body: "Create a clean merge request with AI-generated descriptions. Human reviewer validates against AC, checks for hallucinated imports and phantom APIs, and approves.", tip: "MR description: What changed, why, how tested, what could break, rollback plan. AI drafts — you verify." },
    ],
    callout: "The loop is tight by design. Every AI output passes through a human gate before it touches the codebase.",
  },
  {
    id: "disciplines",
    order: 4,
    layout: "pillars",
    title: "Engineering Disciplines",
    subtitle: "Context engineering, prompt craft, tooling, and documentation.",
    color: "#14B8A6",
    colorLight: "#5EEAD4",
    colorGlow: "rgba(20,184,166,0.3)",
    icon: "🔬",
    headline: "Core Engineering Disciplines",
    pillars: [
      { icon: "🧠", title: "Context Engineering", items: ["Curate what the model sees — architecture docs, coding standards, data models, relevant code", "Use system prompts and project-level instructions to steer output", "Manage context window budget — prioritize signal over noise", "Build reusable context packs per project area"] },
      { icon: "✍️", title: "Prompt Engineering", items: ["Standardized prompt templates for recurring tasks", "Version-control prompts alongside code — they are engineering artifacts", "Use structured output formats (XML, JSON schemas)", "Iterate prompts like code: test, measure, refine"] },
      { icon: "🔧", title: "Tool & Skill Dev", items: ["Build MCP servers for structured access to internal services", "Create custom Sidekick Skills encoding team conventions", "Develop reusable tool chains — composable capabilities", "Evaluate tools: Copilot for code gen, Sidekick for reasoning, M365 Copilot for docs"] },
    ],
    results: [
      { val: "ADR", label: "Architecture Decision Records" },
      { val: "ICD", label: "Interface Control Docs" },
      { val: "SDD", label: "System Design Docs" },
      { val: "SIP", label: "System Integration Plans" },
    ],
    callout: "AI can draft ADR, ICD, IMS, SDD, SIP, changelogs, and onboarding guides — but a human must validate accuracy before any doc is baselined.",
  },
  {
    id: "qa",
    order: 5,
    layout: "info-cards",
    title: "QA & Testing",
    subtitle: "How front-end QA testers leverage AI for testing at speed.",
    color: "#EC4899",
    colorLight: "#F472B6",
    colorGlow: "rgba(236,72,153,0.3)",
    icon: "🧪",
    headline: "QA Testers & AI",
    subheadline: "From manual testing to AI-assisted test automation.",
    banner: "Front-end QA testers can use AI to learn and write Playwright tests for our Razor Pages front-end, augment manual testing, and contribute directly to our CI/CD pipeline.",
    cards: [
      { stat: "E2E", statLabel: "Playwright", title: "Learning Playwright with AI", body: "Use AI as a tutor: paste a Razor Page component and ask it to explain how to write a Playwright test. Start simple, then build to form interactions and visual regression." },
      { stat: "CI/CD", statLabel: "Pipeline", title: "Tests in the Pipeline", body: "AI-generated Playwright tests go into the CI/CD pipeline. Every automated test is one less manual regression cycle. Focus on critical happy paths first." },
      { stat: "Manual+", statLabel: "Augmented", title: "Augmenting Manual Testing", body: "Use AI to generate test case matrices from acceptance criteria, identify edge cases, and draft defect reports with reproduction steps." },
      { stat: "RTM", statLabel: "Traceability", title: "Test Coverage Mapping", body: "AI maps test cases back to requirements for traceability. Feed it your AC and test suite — it identifies coverage gaps faster than manual review." },
    ],
    callout: "QA doesn't need to become engineering. But QA that speaks the language of automation multiplies the whole team's velocity.",
  },
  {
    id: "functional",
    order: 6,
    layout: "checklist",
    title: "Functional Team",
    subtitle: "RTM, use cases, roadmaps, and documentation — AI's role and limits.",
    color: "#06B6D4",
    colorLight: "#22D3EE",
    colorGlow: "rgba(6,182,212,0.3)",
    icon: "📊",
    headline: "Functional Team AI Use Cases",
    approved: [
      { icon: "✅", title: "RTM Development", desc: "Draft RTMs from user stories and test cases. M365 Copilot in Excel for structured data, Sidekick for narrative. Human validation mandatory." },
      { icon: "✅", title: "Use Case Documentation", desc: "Generate use case templates and exception flows. M365 Copilot in Word for drafting. You own the content." },
      { icon: "✅", title: "Product Roadmap Drafting", desc: "Synthesize backlog and sprint outcomes into roadmap narratives. M365 Copilot in PowerPoint for presentations." },
      { icon: "✅", title: "Meeting Summaries", desc: "Structure notes into summaries, decisions, and action items. Approved tools only — never upload recordings with CUI." },
      { icon: "✅", title: "Process Documentation", desc: "SOPs, workflow diagrams, onboarding guides — AI drafts, humans refine. Version control all documentation." },
    ],
    forbidden: [
      { icon: "🚫", title: "Loading CUI Documents", desc: "Never upload or paste CUI-marked documents, FOUO data, or controlled technical information into any AI tool." },
      { icon: "🚫", title: "Client Data in Prompts", desc: "No beneficiary names, case data, claim numbers, or client-specific PII. Use sanitized examples." },
      { icon: "🚫", title: "Deliverable Without Review", desc: "AI-drafted deliverables must be reviewed for accuracy and compliance before sharing with the client." },
      { icon: "🚫", title: "Replacing Human Analysis", desc: "AI summarizes and structures — it doesn't analyze policy implications or assess risk. That's your job." },
    ],
    callout: "AI is your drafting assistant, not your analyst. It structures information — you validate meaning.",
  },
  {
    id: "compliance",
    order: 7,
    layout: "catalog",
    title: "Data & Compliance",
    subtitle: "CUI, PII, and the non-negotiable rules of data handling.",
    color: "#EF4444",
    colorLight: "#F87171",
    colorGlow: "rgba(239,68,68,0.3)",
    icon: "🔐",
    headline: "Data Classification & AI Boundaries",
    subheadline: "Know your data. Know your limits. No exceptions.",
    categories: [
      { title: "🚨 Never Input to AI", color: "#EF4444", items: [
        { label: "CUI / FOUO", desc: "Controlled Unclassified Information — strictly prohibited from any AI tool." },
        { label: "PII", desc: "Names, SSNs, dates of birth, addresses, case numbers, beneficiary data." },
        { label: "Credentials & Secrets", desc: "API keys, tokens, passwords, connection strings, certificates, private keys." },
        { label: "Production Data", desc: "Real database contents, production logs with user data, client system exports." },
      ]},
      { title: "⚠️ Use with Caution", color: "#F59E0B", items: [
        { label: "Internal Architecture Docs", desc: "Sanitize system names and endpoints. Remove environment-specific details." },
        { label: "Ticket Descriptions", desc: "Scrub client names, project codes, and specific data references first." },
        { label: "Code Patterns", desc: "Generic patterns fine. Strip comments referencing client systems, file paths, config values." },
      ]},
      { title: "✅ Safe for AI Use", color: "#22C55E", items: [
        { label: "Open Source Code", desc: "Publicly available code, libraries, frameworks. No restrictions." },
        { label: "General Technical Questions", desc: "Language features, framework patterns, best practices — all unrestricted." },
        { label: "Sanitized Examples", desc: "Anonymized code with placeholder data, generic variable names." },
        { label: "Learning & Exploration", desc: "New technologies, design patterns, skill building — use AI freely." },
      ]},
    ],
    callout: "When in doubt, don't paste it. Ask your lead. There is no 'undo' once data enters an AI model's context window.",
  },
];
