"""Report-writing and alignment recommendation functions for the model bakeoff."""

from __future__ import annotations

import json
import logging
from datetime import datetime, timezone
from typing import Any, TYPE_CHECKING

if TYPE_CHECKING:
    from pathlib import Path

logger = logging.getLogger(__name__)


def _recommend_alignment(results: list[dict[str, Any]]) -> dict[str, str | None]:
    if not results:
        return {"small": None, "heavy": None}

    heavy = results[0]["model"]

    # Prefer fast + decent for small model.
    small_ranked = sorted(
        results,
        key=lambda r: (
            r["task_score"] - (r["avg_latency_s"] * 0.8),
            r["success_rate"],
        ),
        reverse=True,
    )
    small = small_ranked[0]["model"] if small_ranked else heavy

    return {"small": small, "heavy": heavy}


def _write_reports(
    out_dir: Path,
    payload: dict[str, Any],
    alignment: dict[str, str | None],
    write_env: Path | None,
) -> tuple[Path, Path]:
    out_dir.mkdir(parents=True, exist_ok=True)
    ts = datetime.now(timezone.utc).strftime("%Y%m%d-%H%M%SZ")

    json_path = out_dir / f"model_bakeoff_{ts}.json"
    md_path = out_dir / f"model_bakeoff_{ts}.md"
    json_path.write_text(json.dumps(payload, indent=2), encoding="utf-8")

    lines: list[str] = []
    lines.append("# Model Bakeoff Report")
    lines.append("")
    lines.append(f"- Generated: `{payload['timestamp_utc']}`")
    lines.append(f"- Models tested: `{payload['summary']['tested_models']}`")
    lines.append(f"- Runnable models: `{payload['summary']['runnable_models']}`")
    lines.append("")
    lines.append("## Recommended Alignment")
    lines.append("")
    lines.append("```env")
    lines.append(f"DEEP_RESEARCH_SMALL_MODEL={alignment.get('small') or ''}")
    lines.append(f"DEEP_RESEARCH_HEAVY_MODEL={alignment.get('heavy') or ''}")
    if alignment.get("small"):
        lines.append(f"AGENTIC_MODEL_TIER_2={alignment['small']}")
    if alignment.get("heavy"):
        lines.append(f"AGENTIC_MODEL_TIER_3={alignment['heavy']}")
        lines.append(f"AGENTIC_MODEL_TIER_4={alignment['heavy']}")
    lines.append("```")
    lines.append("")
    lines.append("## Ranking")
    lines.append("")
    lines.append(
        "| Rank | Model | Provider | Overall | Task Score | Success | Avg Latency (s) |"
    )
    lines.append("| --- | --- | --- | ---: | ---: | ---: | ---: |")
    for idx, row in enumerate(payload["results"], start=1):
        lines.append(
            f"| {idx} | `{row['model']}` | `{row['provider']}` | "
            f"{row['overall_score']:.2f} | {row['task_score']:.2f} | "
            f"{row['success_rate']:.2%} | {row['avg_latency_s']:.3f} |"
        )
    lines.append("")
    lines.append(f"- JSON details: `{json_path}`")
    md_path.write_text("\n".join(lines), encoding="utf-8")

    if write_env:
        write_env.parent.mkdir(parents=True, exist_ok=True)
        env_lines = [
            f"# Generated by tools/llm/model_bakeoff.py at {payload['timestamp_utc']}",
            f"DEEP_RESEARCH_SMALL_MODEL={alignment.get('small') or ''}",
            f"DEEP_RESEARCH_HEAVY_MODEL={alignment.get('heavy') or ''}",
        ]
        if alignment.get("small"):
            env_lines.append(f"AGENTIC_MODEL_TIER_2={alignment['small']}")
        if alignment.get("heavy"):
            env_lines.append(f"AGENTIC_MODEL_TIER_3={alignment['heavy']}")
            env_lines.append(f"AGENTIC_MODEL_TIER_4={alignment['heavy']}")
        write_env.write_text("\n".join(env_lines) + "\n", encoding="utf-8")

    return json_path, md_path
